-- < 연도별 대장균 크기의 편차 구하기 >
-- https://school.programmers.co.kr/learn/courses/30/lessons/299310

-- mysql
WITH MAX_SIZE_BY_YEAR
AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE))
    
SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR,
       (B.MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV,
       ID
FROM ECOLI_DATA A
     JOIN MAX_SIZE_BY_YEAR B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY 1, 2;
