-- < 상품을 구매한 회원 비율 구하기 >
-- 문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/131534

SELECT YEAR(A.SALES_DATE) as YEAR,
        MONTH(A.SALES_DATE) as MONTH,
        COUNT(DISTINCT(A.USER_ID)) as PUCHASED_USERS,
        ROUND((COUNT(DISTINCT(A.USER_ID))) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) as PUCHASED_RATIO
FROM ONLINE_SALE A JOIN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021) B
    ON A.USER_ID = B.USER_ID
GROUP BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE)
ORDER BY YEAR, MONTH;
